sudo: required
services:
  - docker

before_install:
  - docker build -t mjkrafael/docker-react -f Dockerfile.dev .

script:
#  - docker run mjkrafael/docker-react npm run test -- --coverage
  - docker run -e CI=true mjkrafael/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-301393399529"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY