sudo: required
services:
  - docker

before_install:
  - docker build -t mjkrafael/docker-react -f Dockerfile.dev .

script:
#  - docker run mjkrafael/docker-react npm run test -- --coverage
  - docker run -e CI=true mjkrafael/docker-react npm run test

